# Lambda Functions
By now, you should be pretty familiar with writing your own functions in Python. Functions allow us to save a logical sequence of operations as a re-usable piece of code.   

Consider the function below, there are a few important pieces that every function requires. We know that a function must be defined using the `def` keyword in Python. Then, [PEP8 convention](https://www.python.org/dev/peps/pep-0008/) states that we should write a detailed docstring so that our function can be understoof by anyone else who might use it. After the docstring, we state the sequence of operations that the function should perform. Finally, we finish off the function with the `return` keyword

In [1]:
def my_function(string, n=6):
    
    ''' return a string n times over '''
    string *= n
    
    return(string)

In [2]:
my_function("hello", 6)

'hellohellohellohellohellohello'

However, we don't always need to be so 'formal' with the way we define functions. Not all functions are so complicated that they require a full docstring, and many functions can actually be defined in one line of code.   

**Lambda functions** give us a quick (and potentially dirty) way of defining simple functions on the fly. Take a look at the code below which carries out the same operation as shown above.

In [3]:
my_function = lambda string, n: string*n

my_function('hello', 6)

'hellohellohellohellohellohello'

## Applying Lambda functions _en masse_
Okay, so that was a pretty simple example. But it is cool to know that we can 'assign' our lambda function to a name so that it persists after it is first defined.   

Now, let's see how lambda functions can be used to apply an operation across an entire column of a Pandas dataframe. We will use the [Iris flower data set](https://en.wikipedia.org/wiki/Iris_flower_data_set) as an example.

In [4]:
from sklearn.datasets import load_iris
import pandas as pd
import numpy as np

# load data set from sk-learn library
iris = load_iris()
# convert to pandas data frame
df = pd.DataFrame(data=np.c_[iris['data'], iris['target']],
                  columns=iris['feature_names'] + ['target'])

In [5]:
df.sample(10)

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),target
110,6.5,3.2,5.1,2.0,2.0
36,5.5,3.5,1.3,0.2,0.0
102,7.1,3.0,5.9,2.1,2.0
75,6.6,3.0,4.4,1.4,1.0
78,6.0,2.9,4.5,1.5,1.0
9,4.9,3.1,1.5,0.1,0.0
27,5.2,3.5,1.5,0.2,0.0
144,6.7,3.3,5.7,2.5,2.0
64,5.6,2.9,3.6,1.3,1.0
80,5.5,2.4,3.8,1.1,1.0

In [6]:
df.shape

(150, 5)

We can see that the data set above has five columns. Each row in the data set represents a single flower that was picked in the original study. The first four columns represent the features that were measured for each flower when it was picked, and the final column represents the species of the flower.   

Currently, the target column is a numeric value. This would be great for fitting a machine learning model, but let's suppose we wanted to display the species names instead - we can use a lambda function to do this!   

We can get the species names from the iris data object that we loaded above:

In [7]:
names = iris['target_names']
print(names)

['setosa' 'versicolor' 'virginica']

We can get the species name that corresponds to each numeric code as well:

In [8]:
print(names[0])
print(names[1])
print(names[2])

setosa
versicolor
virginica

Let's first use a lambda function to convert all of the numbers in the `target` column from floats to integers. To do this, we are going to make use of a method called `apply`:

In [9]:
df['target'] = df['target'].apply(lambda x: int(x))
df.head()

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),target
0,5.1,3.5,1.4,0.2,0
1,4.9,3.0,1.4,0.2,0
2,4.7,3.2,1.3,0.2,0
3,4.6,3.1,1.5,0.2,0
4,5.0,3.6,1.4,0.2,0

The apply method is also super useful, as it allowed us to convert all of the values in the column to integers without needing to use a for-loop. Also notice how we did not need to bind our lambda function to a name as we did in the first example.   

Now let's use a second function to convert the numbers to species names:

In [11]:
df['target'] = df['target'].apply(lambda x: names[x])
df

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),target
0,5.1,3.5,1.4,0.2,setosa
1,4.9,3.0,1.4,0.2,setosa
2,4.7,3.2,1.3,0.2,setosa
3,4.6,3.1,1.5,0.2,setosa
4,5.0,3.6,1.4,0.2,setosa
5,5.4,3.9,1.7,0.4,setosa
6,4.6,3.4,1.4,0.3,setosa
7,5.0,3.4,1.5,0.2,setosa
8,4.4,2.9,1.4,0.2,setosa
9,4.9,3.1,1.5,0.1,setosa
10,5.4,3.7,1.5,0.2,setosa
11,4.8,3.4,1.6,0.2,setosa
12,4.8,3.0,1.4,0.1,setosa
13,4.3,3.0,1.1,0.1,setosa
14,5.8,4.0,1.2,0.2,setosa
15,5.7,4.4,1.5,0.4,setosa
16,5.4,3.9,1.3,0.4,setosa
17,5.1,3.5,1.4,0.3,setosa
18,5.7,3.8,1.7,0.3,setosa
19,5.1,3.8,1.5,0.3,setosa
20,5.4,3.4,1.7,0.2,setosa
21,5.1,3.7,1.5,0.4,setosa
22,4.6,3.6,1.0,0.2,setosa
23,5.1,3.3,1.7,0.5,setosa
24,4.8,3.4,1.9,0.2,setosa
25,5.0,3.0,1.6,0.2,setosa
26,5.0,3.4,1.6,0.4,setosa
27,5.2,3.5,1.5,0.2,setosa
28,5.2,3.4,1.4,0.2,setosa
29,4.7,3.2,1.6,0.2,setosa
...,...,...,...,...,...
120,6.9,3.2,5.7,2.3,virginica
121,5.6,2.8,4.9,2.0,virginica
122,7.7,2.8,6.7,2.0,virginica
123,6.3,2.7,4.9,1.8,virginica
124,6.7,3.3,5.7,2.1,virginica
125,7.2,3.2,6.0,1.8,virginica
126,6.2,2.8,4.8,1.8,virginica
127,6.1,3.0,4.9,1.8,virginica
128,6.4,2.8,5.6,2.1,virginica
129,7.2,3.0,5.8,1.6,virginica
130,7.4,2.8,6.1,1.9,virginica
131,7.9,3.8,6.4,2.0,virginica
132,6.4,2.8,5.6,2.2,virginica
133,6.3,2.8,5.1,1.5,virginica
134,6.1,2.6,5.6,1.4,virginica
135,7.7,3.0,6.1,2.3,virginica
136,6.3,3.4,5.6,2.4,virginica
137,6.4,3.1,5.5,1.8,virginica
138,6.0,3.0,4.8,1.8,virginica
139,6.9,3.1,5.4,2.1,virginica
140,6.7,3.1,5.6,2.4,virginica
141,6.9,3.1,5.1,2.3,virginica
142,5.8,2.7,5.1,1.9,virginica
143,6.8,3.2,5.9,2.3,virginica
144,6.7,3.3,5.7,2.5,virginica
145,6.7,3.0,5.2,2.3,virginica
146,6.3,2.5,5.0,1.9,virginica
147,6.5,3.0,5.2,2.0,virginica
148,6.2,3.4,5.4,2.3,virginica
149,5.9,3.0,5.1,1.8,virginica

## A closing note on lambda functions
Lambda functions are great, they allow us to write simple functions with minimal code. However, just because they require fewer lines of code, this does not necessarily mean that they are the best way of writing functions.   

There is huge value in writing functions with detailed docstrings that other people can understand when looking at your code. When using a lambda function, put yourself in the shoes of another person viewing your code. 

Before using a lambda function ask yourself "Will the shortened lambda function really add value to someone else reading my code or is it just going to add confusion?"

### Happy coding!